### ISSUE TITLE
Comentários dos tickets não devem aparecer listagens

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#98]

**Comment by leogermani** [comment]
Os comentários que são respostas dos tickets estão aparecendo na listagem geral de moderação de comentários do admin. Também estão aparecendo no widget de comentários, se vc colocá-lo na barra lateral. 

Não devem aparecer! Acho que tem que usar outro status pra eles não aparecerem nesses lugares

**Comment by leogermani** [comment]
Tá dando erro ao tentar responder a um ticket pelo admin:

```
Notice: Undefined variable: user in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 532

Notice: Trying to get property of non-object in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 532

Notice: Undefined variable: user in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 533

Notice: Trying to get property of non-object in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 533

Notice: Undefined variable: user in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 534

Notice: Trying to get property of non-object in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 534

Notice: Undefined variable: user in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 535

Notice: Trying to get property of non-object in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 535

Notice: Undefined variable: wpdb in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 540

Fatal error: Uncaught Error: Call to a member function update() on null in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php:540 Stack trace: #0 /home/leo/devel/rhs/public/wp/wp-includes/class-wp-hook.php(300): RHSTicket->save_wp_editor_fields(99159) #1 /home/leo/devel/rhs/public/wp/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #2 /home/leo/devel/rhs/public/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/leo/devel/rhs/public/wp/wp-includes/post.php(3510): do_action('save_post', 99159, Object(WP_Post), true) #4 /home/leo/devel/rhs/public/wp/wp-includes/post.php(3583): wp_insert_post(Array, false) #5 /home/leo/devel/rhs/public/wp/wp-admin/includes/post.php(378): wp_update_post(Array) #6 /home/leo/devel/rhs/public/wp/wp-admin/post.php(193): edit_post() #7 {main} thrown in /home/leo/devel/rhs/public/wp-content/themes/rhs/inc/ticket/ticket.php on line 540
```
